import type { CapacitorConfig } from "@capacitor/cli";

// Capacitor config for hermes-mobile. `webDir` points at the Vite build
// output; the Android project under `./android/` is generated by
// `npx cap add android` and synced by `pnpm cap:sync`.

const config: CapacitorConfig = {
  appId: "com.nousresearch.hermes",
  appName: "Hermes Agent",
  webDir: "dist",
  android: {
    allowMixedContent: false,
    backgroundColor: "#0b0b0b",
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 1500,
      backgroundColor: "#0b0b0b",
      showSpinner: false,
    },
    StatusBar: {
      style: "DARK",
      backgroundColor: "#000000",
      overlaysWebView: true,
    },
  },
};

export default config;
