#!/usr/bin/env bash
# check-kotlin-drift.sh — verify the android-runner/ Kotlin tree and
# the live apps/mobile/android/ Kotlin tree are in sync. Exits non-zero
# on any divergence. Designed to be run in CI after every build.
#
# Per groovy-fluttering-island.md Phase 0c, android-runner/ is the
# single source of truth for the Hermes Kotlin sources. The live tree
# is regenerated by apps/mobile/scripts/setup-android.sh on every
# build. Drift between the two means a developer edited the live tree
# directly without going through the runner, or the sync script was
# skipped.
#
# Usage:  bash script/check-kotlin-drift.sh
# Output: diff (if any); exit 0 if identical, exit 1 if different.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNNER="$ROOT/android-runner/app/src/main/kotlin/com/nousresearch/hermes"
LIVE="$ROOT/apps/mobile/android/app/src/main/kotlin/com/nousresearch/hermes"

if [[ ! -d "$RUNNER" ]]; then
  echo "error: $RUNNER does not exist" >&2
  exit 1
fi

if [[ ! -d "$LIVE" ]]; then
  echo "error: $LIVE does not exist. Run \`bash apps/mobile/scripts/setup-android.sh\` first." >&2
  exit 1
fi

# Use rsync's dry-run + itemize-changes mode to detect differences
# (added, deleted, modified) without writing anything. Cleaner than
# `diff -rq` for CI logs.
DRIFT=$(rsync -a --delete --dry-run --itemize-changes \
  --exclude='.DS_Store' \
  "$RUNNER/" "$LIVE/" 2>&1 | grep -v '^\.' || true)

if [[ -n "$DRIFT" ]]; then
  echo "Kotlin drift detected between android-runner/ and apps/mobile/android/:" >&2
  echo "" >&2
  echo "$DRIFT" >&2
  echo "" >&2
  echo "Fix: edit android-runner/, then run \`bash apps/mobile/scripts/setup-android.sh\`" >&2
  echo "     to regenerate the live tree. Or revert direct edits to the live tree." >&2
  exit 1
fi

echo "OK: android-runner/ and apps/mobile/android/ are in sync ($(find "$RUNNER" -name '*.kt' | wc -l) Kotlin files)"
