package com.nousresearch.hermes.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.nousresearch.hermes.chat.MessageEntity

/**
 * Data-access object for the `messages` table. Phase A only needs
 * three queries: `insert` for a single message, `listForSession`
 * to rehydrate the chat list, and `listSessions` to populate the
 * (placeholder) Sessions tab.
 *
 * The aggregation in `listSessions` is a single `@Query` rather
 * than a SQL VIEW — Room emits one prepared statement, and we
 * don't need the reusability of a view for Phase A's footprint.
 */
@Dao
interface MessageDao {

    /** Insert (or replace on conflict) a single message. The
     *  autogenerated [MessageEntity.id] is returned so the caller
     *  can wire `parentAssistantId` for follow-up reasoning/tool
     *  rows in the same turn. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(message: MessageEntity): Long

    /** Replay a session in chronological order. */
    @Query("SELECT * FROM messages WHERE session_id = :sessionId ORDER BY timestamp ASC, id ASC")
    suspend fun listForSession(sessionId: String): List<MessageEntity>

    /** Aggregate query: one row per session, with message count
     *  and the first user message as a preview snippet. Computed
     *  in Kotlin (see `listSessions` extension in [HermesDatabase])
     *  rather than in SQL — Room's KSP processor struggles with
     *  the subquery pattern in 2.6.1 + KSP 2.0.4. */
    @Query("SELECT * FROM messages ORDER BY timestamp ASC, id ASC")
    suspend fun listAllMessages(): List<MessageEntity>

    /** Hard-delete all messages for one session. Used by
     *  the (Phase D) "clear session" flow. */
    @Query("DELETE FROM messages WHERE session_id = :sessionId")
    suspend fun deleteSession(sessionId: String): Int

    /** Count distinct session ids — a sanity check that the
     *  `listSessions` aggregation agrees with a direct count. */
    @Query("SELECT COUNT(DISTINCT session_id) FROM messages")
    suspend fun sessionCount(): Int
}
